load("@rules_go//go:def.bzl", "go_library")

package(
    default_visibility = ["//gazelle/gleam:__subpackages__"],
)

go_library(
    name = "parser",
    srcs = ["parser.go"],
    importpath = "github.com/iocat/rules_gleam/gazelle/gleam/parser",
)
