// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

// -----------------------------------------------------------------------------
// ## Go Helper Code
// -----------------------------------------------------------------------------
func toSlice[T any](v any) []T {
	if v == nil {
		return nil
	}
	if s, ok := v.([]any); ok {
		res := make([]T, len(s))
		for i, item := range s {
			res[i] = item.(T)
		}
		return res
	}
	val, ok := v.(T)
	if !ok {
		panic(fmt.Sprintf("failed to convert to slice: unexpected type %T for target type %T", v, *new(T)))
	}
	return []T{val}
}

// Helper functions for parsing literals
func parseInteger(text []byte) (int64, error) {
	s := strings.ReplaceAll(string(text), "_", "")
	if len(s) > 2 {
		switch s[0:2] {
		case "0x", "0X":
			return strconv.ParseInt(s[2:], 16, 64)
		case "0o", "0O":
			return strconv.ParseInt(s[2:], 8, 64)
		case "0b", "0B":
			return strconv.ParseInt(s[2:], 2, 64)
		}
	}
	return strconv.ParseInt(s, 10, 64)
}

func parseFloat(text []byte) (float64, error) {
	s := strings.ReplaceAll(string(text), "_", "")
	return strconv.ParseFloat(s, 64)
}

func unquoteString(text []byte) (string, error) { return strconv.Unquote(string(text)) }

// -----------------------------------------------------------------------------
// ## AST Node Definitions
// -----------------------------------------------------------------------------

type Node interface{}
type Statement interface{ Node }
type Expression interface{ Node }
type Type interface{ Node }
type Pattern interface{ Node }

type SourceFile struct{ Statements []Node }
type Identifier struct{ Name string }
type Discard struct{ Name string }
type Parameter struct {
	Label, Name string
	Type        Type
}
type Function struct {
	Public             bool
	Name               string
	Parameters         []Parameter
	ReturnType         Type
	ExternalAttributes []ExternalAttribute
}
type Import struct {
	Module      string
	Unqualified []UnqualifiedImport
	Alias       string
}
type ExternalAttribute struct {
	TargetLang string
	Module     string
	Function   string
}

// Represents a single item in an unqualified import list, e.g., `MyType` in `import gleam.{MyType}`.
type UnqualifiedImport struct {
	Name   string
	Alias  string
	IsType bool // Differentiates `type MyType` from `MyFunction`
}

var g = &grammar{
	rules: []*rule{
		{
			name: "SourceFile",
			pos:  position{line: 92, col: 1, offset: 2546},
			expr: &actionExpr{
				pos: position{line: 92, col: 15, offset: 2560},
				run: (*parser).callonSourceFile1,
				expr: &seqExpr{
					pos: position{line: 92, col: 15, offset: 2560},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 92, col: 15, offset: 2560},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 17, offset: 2562},
							label: "first",
							expr: &zeroOrOneExpr{
								pos: position{line: 92, col: 23, offset: 2568},
								expr: &choiceExpr{
									pos: position{line: 92, col: 24, offset: 2569},
									alternatives: []any{
										&ruleRefExpr{
											pos:  position{line: 92, col: 24, offset: 2569},
											name: "Import",
										},
										&ruleRefExpr{
											pos:  position{line: 92, col: 33, offset: 2578},
											name: "Function",
										},
										&ruleRefExpr{
											pos:  position{line: 92, col: 44, offset: 2589},
											name: "IgnoredContent",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 92, col: 61, offset: 2606},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 92, col: 66, offset: 2611},
								expr: &seqExpr{
									pos: position{line: 92, col: 67, offset: 2612},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 92, col: 67, offset: 2612},
											name: "_",
										},
										&choiceExpr{
											pos: position{line: 92, col: 70, offset: 2615},
											alternatives: []any{
												&ruleRefExpr{
													pos:  position{line: 92, col: 70, offset: 2615},
													name: "Import",
												},
												&ruleRefExpr{
													pos:  position{line: 92, col: 79, offset: 2624},
													name: "Function",
												},
												&ruleRefExpr{
													pos:  position{line: 92, col: 90, offset: 2635},
													name: "IgnoredContent",
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 108, offset: 2653},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 110, offset: 2655},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 109, col: 1, offset: 3046},
			expr: &actionExpr{
				pos: position{line: 109, col: 13, offset: 3058},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 109, col: 13, offset: 3058},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 109, col: 13, offset: 3058},
							label: "attrs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 109, col: 19, offset: 3064},
								expr: &ruleRefExpr{
									pos:  position{line: 109, col: 19, offset: 3064},
									name: "ExternalAttribute",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 109, col: 38, offset: 3083},
							label: "pub",
							expr: &zeroOrOneExpr{
								pos: position{line: 109, col: 42, offset: 3087},
								expr: &seqExpr{
									pos: position{line: 109, col: 43, offset: 3088},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 109, col: 43, offset: 3088},
											val:        "pub",
											ignoreCase: false,
											want:       "\"pub\"",
										},
										&ruleRefExpr{
											pos:  position{line: 109, col: 49, offset: 3094},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 109, col: 54, offset: 3099},
							val:        "fn",
							ignoreCase: false,
							want:       "\"fn\"",
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 59, offset: 3104},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 62, offset: 3107},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 109, col: 67, offset: 3112},
								name: "Name",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 72, offset: 3117},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 74, offset: 3119},
							label: "params",
							expr: &ruleRefExpr{
								pos:  position{line: 109, col: 81, offset: 3126},
								name: "FunctionParameters",
							},
						},
						&labeledExpr{
							pos:   position{line: 109, col: 100, offset: 3145},
							label: "returnGroup",
							expr: &zeroOrOneExpr{
								pos: position{line: 109, col: 112, offset: 3157},
								expr: &seqExpr{
									pos: position{line: 109, col: 113, offset: 3158},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 109, col: 113, offset: 3158},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 109, col: 115, offset: 3160},
											val:        "->",
											ignoreCase: false,
											want:       "\"->\"",
										},
										&ruleRefExpr{
											pos:  position{line: 109, col: 120, offset: 3165},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 109, col: 122, offset: 3167},
											name: "Type",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 129, offset: 3174},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 131, offset: 3176},
							label: "body",
							expr: &zeroOrOneExpr{
								pos: position{line: 109, col: 136, offset: 3181},
								expr: &ruleRefExpr{
									pos:  position{line: 109, col: 136, offset: 3181},
									name: "IgnoredBlock",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ExternalAttribute",
			pos:  position{line: 121, col: 1, offset: 3600},
			expr: &actionExpr{
				pos: position{line: 121, col: 22, offset: 3621},
				run: (*parser).callonExternalAttribute1,
				expr: &seqExpr{
					pos: position{line: 121, col: 22, offset: 3621},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 121, col: 22, offset: 3621},
							val:        "@",
							ignoreCase: false,
							want:       "\"@\"",
						},
						&ruleRefExpr{
							pos:  position{line: 121, col: 26, offset: 3625},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 121, col: 28, offset: 3627},
							val:        "external",
							ignoreCase: false,
							want:       "\"external\"",
						},
						&ruleRefExpr{
							pos:  position{line: 121, col: 39, offset: 3638},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 121, col: 41, offset: 3640},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 121, col: 45, offset: 3644},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 121, col: 47, offset: 3646},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 121, col: 52, offset: 3651},
								name: "ExternalArgs",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 121, col: 65, offset: 3664},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 121, col: 67, offset: 3666},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 121, col: 71, offset: 3670},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "ExternalArgs",
			pos:  position{line: 126, col: 1, offset: 3766},
			expr: &actionExpr{
				pos: position{line: 126, col: 17, offset: 3782},
				run: (*parser).callonExternalArgs1,
				expr: &seqExpr{
					pos: position{line: 126, col: 17, offset: 3782},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 126, col: 17, offset: 3782},
							label: "target",
							expr: &choiceExpr{
								pos: position{line: 126, col: 25, offset: 3790},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 126, col: 25, offset: 3790},
										val:        "erlang",
										ignoreCase: false,
										want:       "\"erlang\"",
									},
									&litMatcher{
										pos:        position{line: 126, col: 36, offset: 3801},
										val:        "javascript",
										ignoreCase: false,
										want:       "\"javascript\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 126, col: 50, offset: 3815},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 126, col: 52, offset: 3817},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 126, col: 56, offset: 3821},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 126, col: 58, offset: 3823},
							label: "module",
							expr: &ruleRefExpr{
								pos:  position{line: 126, col: 65, offset: 3830},
								name: "StringArg",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 126, col: 75, offset: 3840},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 126, col: 77, offset: 3842},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 126, col: 81, offset: 3846},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 126, col: 83, offset: 3848},
							label: "function",
							expr: &ruleRefExpr{
								pos:  position{line: 126, col: 92, offset: 3857},
								name: "StringArg",
							},
						},
					},
				},
			},
		},
		{
			name: "StringArg",
			pos:  position{line: 134, col: 1, offset: 4049},
			expr: &actionExpr{
				pos: position{line: 134, col: 14, offset: 4062},
				run: (*parser).callonStringArg1,
				expr: &seqExpr{
					pos: position{line: 134, col: 14, offset: 4062},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 134, col: 14, offset: 4062},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 134, col: 19, offset: 4067},
							expr: &charClassMatcher{
								pos:        position{line: 134, col: 19, offset: 4067},
								val:        "[^\"]",
								chars:      []rune{'"'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 134, col: 25, offset: 4073},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "FunctionParameters",
			pos:  position{line: 136, col: 1, offset: 4110},
			expr: &actionExpr{
				pos: position{line: 136, col: 23, offset: 4132},
				run: (*parser).callonFunctionParameters1,
				expr: &seqExpr{
					pos: position{line: 136, col: 23, offset: 4132},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 136, col: 23, offset: 4132},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 136, col: 27, offset: 4136},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 136, col: 29, offset: 4138},
							label: "first",
							expr: &zeroOrOneExpr{
								pos: position{line: 136, col: 35, offset: 4144},
								expr: &ruleRefExpr{
									pos:  position{line: 136, col: 35, offset: 4144},
									name: "FunctionParameter",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 136, col: 54, offset: 4163},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 136, col: 59, offset: 4168},
								expr: &seqExpr{
									pos: position{line: 136, col: 60, offset: 4169},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 136, col: 60, offset: 4169},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 136, col: 62, offset: 4171},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 136, col: 66, offset: 4175},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 136, col: 68, offset: 4177},
											name: "FunctionParameter",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 136, col: 88, offset: 4197},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 136, col: 90, offset: 4199},
							expr: &litMatcher{
								pos:        position{line: 136, col: 90, offset: 4199},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 136, col: 95, offset: 4204},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 136, col: 97, offset: 4206},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "LambdaFunction",
			pos:  position{line: 152, col: 1, offset: 4633},
			expr: &actionExpr{
				pos: position{line: 152, col: 19, offset: 4651},
				run: (*parser).callonLambdaFunction1,
				expr: &seqExpr{
					pos: position{line: 152, col: 19, offset: 4651},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 152, col: 19, offset: 4651},
							val:        "fn",
							ignoreCase: false,
							want:       "\"fn\"",
						},
						&ruleRefExpr{
							pos:  position{line: 152, col: 24, offset: 4656},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 152, col: 26, offset: 4658},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 152, col: 30, offset: 4662},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 152, col: 32, offset: 4664},
							label: "first",
							expr: &zeroOrOneExpr{
								pos: position{line: 152, col: 38, offset: 4670},
								expr: &ruleRefExpr{
									pos:  position{line: 152, col: 38, offset: 4670},
									name: "LambdaFunctionParameter",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 152, col: 63, offset: 4695},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 152, col: 68, offset: 4700},
								expr: &seqExpr{
									pos: position{line: 152, col: 69, offset: 4701},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 152, col: 69, offset: 4701},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 152, col: 71, offset: 4703},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 75, offset: 4707},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 77, offset: 4709},
											name: "LambdaFunctionParameter",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 152, col: 104, offset: 4736},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 152, col: 106, offset: 4738},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&labeledExpr{
							pos:   position{line: 152, col: 110, offset: 4742},
							label: "returnGroup",
							expr: &zeroOrOneExpr{
								pos: position{line: 152, col: 122, offset: 4754},
								expr: &seqExpr{
									pos: position{line: 152, col: 123, offset: 4755},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 152, col: 123, offset: 4755},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 152, col: 125, offset: 4757},
											val:        "->",
											ignoreCase: false,
											want:       "\"->\"",
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 130, offset: 4762},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 132, offset: 4764},
											name: "LambdaFunctionParameter",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LambdaFunctionParameter",
			pos:  position{line: 155, col: 1, offset: 4814},
			expr: &actionExpr{
				pos: position{line: 155, col: 28, offset: 4841},
				run: (*parser).callonLambdaFunctionParameter1,
				expr: &labeledExpr{
					pos:   position{line: 155, col: 28, offset: 4841},
					label: "t",
					expr: &choiceExpr{
						pos: position{line: 155, col: 31, offset: 4844},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 155, col: 31, offset: 4844},
								name: "LambdaFunction",
							},
							&ruleRefExpr{
								pos:  position{line: 155, col: 48, offset: 4861},
								name: "Type",
							},
							&ruleRefExpr{
								pos:  position{line: 155, col: 55, offset: 4868},
								name: "TupleType",
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionParameter",
			pos:  position{line: 157, col: 1, offset: 4898},
			expr: &actionExpr{
				pos: position{line: 157, col: 22, offset: 4919},
				run: (*parser).callonFunctionParameter1,
				expr: &seqExpr{
					pos: position{line: 157, col: 22, offset: 4919},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 157, col: 22, offset: 4919},
							label: "p",
							expr: &choiceExpr{
								pos: position{line: 157, col: 25, offset: 4922},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 157, col: 25, offset: 4922},
										name: "LabeledNameParam",
									},
									&ruleRefExpr{
										pos:  position{line: 157, col: 44, offset: 4941},
										name: "NameParam",
									},
									&ruleRefExpr{
										pos:  position{line: 157, col: 56, offset: 4953},
										name: "DiscardParam",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 157, col: 70, offset: 4967},
							label: "typ",
							expr: &zeroOrOneExpr{
								pos: position{line: 157, col: 74, offset: 4971},
								expr: &ruleRefExpr{
									pos:  position{line: 157, col: 74, offset: 4971},
									name: "TypeAnnotation",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TypeAnnotation",
			pos:  position{line: 165, col: 1, offset: 5124},
			expr: &actionExpr{
				pos: position{line: 165, col: 19, offset: 5142},
				run: (*parser).callonTypeAnnotation1,
				expr: &seqExpr{
					pos: position{line: 165, col: 19, offset: 5142},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 165, col: 19, offset: 5142},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 165, col: 23, offset: 5146},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 165, col: 25, offset: 5148},
							label: "t",
							expr: &ruleRefExpr{
								pos:  position{line: 165, col: 28, offset: 5151},
								name: "TypeAnnotationContent",
							},
						},
					},
				},
			},
		},
		{
			name: "TypeAnnotationContent",
			pos:  position{line: 166, col: 1, offset: 5192},
			expr: &actionExpr{
				pos: position{line: 166, col: 26, offset: 5217},
				run: (*parser).callonTypeAnnotationContent1,
				expr: &labeledExpr{
					pos:   position{line: 166, col: 26, offset: 5217},
					label: "t",
					expr: &choiceExpr{
						pos: position{line: 166, col: 29, offset: 5220},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 166, col: 29, offset: 5220},
								name: "LambdaFunction",
							},
							&ruleRefExpr{
								pos:  position{line: 166, col: 46, offset: 5237},
								name: "TupleType",
							},
							&ruleRefExpr{
								pos:  position{line: 166, col: 58, offset: 5249},
								name: "Type",
							},
						},
					},
				},
			},
		},
		{
			name: "TupleType",
			pos:  position{line: 167, col: 1, offset: 5272},
			expr: &actionExpr{
				pos: position{line: 167, col: 14, offset: 5285},
				run: (*parser).callonTupleType1,
				expr: &seqExpr{
					pos: position{line: 167, col: 14, offset: 5285},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 167, col: 14, offset: 5285},
							val:        "#(",
							ignoreCase: false,
							want:       "\"#(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 167, col: 19, offset: 5290},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 167, col: 21, offset: 5292},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 167, col: 28, offset: 5299},
								name: "TypeAnnotationContent",
							},
						},
						&labeledExpr{
							pos:   position{line: 167, col: 51, offset: 5322},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 167, col: 56, offset: 5327},
								expr: &seqExpr{
									pos: position{line: 167, col: 57, offset: 5328},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 167, col: 57, offset: 5328},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 167, col: 59, offset: 5330},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 167, col: 63, offset: 5334},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 167, col: 65, offset: 5336},
											name: "TypeAnnotationContent",
										},
										&ruleRefExpr{
											pos:  position{line: 167, col: 87, offset: 5358},
											name: "_",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 167, col: 91, offset: 5362},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 167, col: 93, offset: 5364},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Type",
			pos:  position{line: 168, col: 1, offset: 5388},
			expr: &actionExpr{
				pos: position{line: 168, col: 9, offset: 5396},
				run: (*parser).callonType1,
				expr: &seqExpr{
					pos: position{line: 168, col: 9, offset: 5396},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 168, col: 9, offset: 5396},
							label: "mod",
							expr: &zeroOrOneExpr{
								pos: position{line: 168, col: 13, offset: 5400},
								expr: &seqExpr{
									pos: position{line: 168, col: 14, offset: 5401},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 168, col: 14, offset: 5401},
											name: "Name",
										},
										&litMatcher{
											pos:        position{line: 168, col: 19, offset: 5406},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 168, col: 25, offset: 5412},
							label: "name",
							expr: &choiceExpr{
								pos: position{line: 168, col: 31, offset: 5418},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 168, col: 31, offset: 5418},
										name: "Name",
									},
									&ruleRefExpr{
										pos:  position{line: 168, col: 38, offset: 5425},
										name: "UpName",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 168, col: 46, offset: 5433},
							expr: &seqExpr{
								pos: position{line: 168, col: 47, offset: 5434},
								exprs: []any{
									&ruleRefExpr{
										pos:  position{line: 168, col: 47, offset: 5434},
										name: "_",
									},
									&labeledExpr{
										pos:   position{line: 168, col: 49, offset: 5436},
										label: "gp",
										expr: &ruleRefExpr{
											pos:  position{line: 168, col: 52, offset: 5439},
											name: "GenericParams",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "GenericParams",
			pos:  position{line: 171, col: 1, offset: 5489},
			expr: &actionExpr{
				pos: position{line: 171, col: 18, offset: 5506},
				run: (*parser).callonGenericParams1,
				expr: &seqExpr{
					pos: position{line: 171, col: 18, offset: 5506},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 171, col: 18, offset: 5506},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 22, offset: 5510},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 171, col: 24, offset: 5512},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 31, offset: 5519},
								name: "TypeAnnotationContent",
							},
						},
						&labeledExpr{
							pos:   position{line: 171, col: 54, offset: 5542},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 171, col: 59, offset: 5547},
								expr: &seqExpr{
									pos: position{line: 171, col: 60, offset: 5548},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 171, col: 60, offset: 5548},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 171, col: 62, offset: 5550},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 171, col: 66, offset: 5554},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 171, col: 68, offset: 5556},
											name: "TypeAnnotationContent",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 92, offset: 5580},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 171, col: 94, offset: 5582},
							expr: &litMatcher{
								pos:        position{line: 171, col: 94, offset: 5582},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
						&litMatcher{
							pos:        position{line: 171, col: 99, offset: 5587},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "GenericParam",
			pos:  position{line: 172, col: 1, offset: 5611},
			expr: &actionExpr{
				pos: position{line: 172, col: 17, offset: 5627},
				run: (*parser).callonGenericParam1,
				expr: &seqExpr{
					pos: position{line: 172, col: 17, offset: 5627},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 172, col: 17, offset: 5627},
							label: "mod",
							expr: &zeroOrOneExpr{
								pos: position{line: 172, col: 21, offset: 5631},
								expr: &seqExpr{
									pos: position{line: 172, col: 22, offset: 5632},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 172, col: 22, offset: 5632},
											name: "Name",
										},
										&litMatcher{
											pos:        position{line: 172, col: 27, offset: 5637},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 172, col: 33, offset: 5643},
							label: "param",
							expr: &choiceExpr{
								pos: position{line: 172, col: 40, offset: 5650},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 172, col: 40, offset: 5650},
										name: "Name",
									},
									&ruleRefExpr{
										pos:  position{line: 172, col: 47, offset: 5657},
										name: "UpName",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 172, col: 55, offset: 5665},
							expr: &seqExpr{
								pos: position{line: 172, col: 56, offset: 5666},
								exprs: []any{
									&ruleRefExpr{
										pos:  position{line: 172, col: 56, offset: 5666},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 172, col: 58, offset: 5668},
										name: "GenericParams",
									},
									&ruleRefExpr{
										pos:  position{line: 172, col: 72, offset: 5682},
										name: "_",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LabeledNameParam",
			pos:  position{line: 173, col: 1, offset: 5706},
			expr: &actionExpr{
				pos: position{line: 173, col: 21, offset: 5726},
				run: (*parser).callonLabeledNameParam1,
				expr: &seqExpr{
					pos: position{line: 173, col: 21, offset: 5726},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 173, col: 21, offset: 5726},
							label: "label",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 27, offset: 5732},
								name: "Label",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 173, col: 33, offset: 5738},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 173, col: 35, offset: 5740},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 40, offset: 5745},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "NameParam",
			pos:  position{line: 176, col: 1, offset: 5836},
			expr: &actionExpr{
				pos: position{line: 176, col: 14, offset: 5849},
				run: (*parser).callonNameParam1,
				expr: &labeledExpr{
					pos:   position{line: 176, col: 14, offset: 5849},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 176, col: 19, offset: 5854},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "DiscardParam",
			pos:  position{line: 177, col: 1, offset: 5921},
			expr: &actionExpr{
				pos: position{line: 177, col: 17, offset: 5937},
				run: (*parser).callonDiscardParam1,
				expr: &labeledExpr{
					pos:   position{line: 177, col: 17, offset: 5937},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 177, col: 22, offset: 5942},
						name: "Discard",
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 178, col: 1, offset: 5997},
			expr: &actionExpr{
				pos: position{line: 178, col: 15, offset: 6011},
				run: (*parser).callonIdentifier1,
				expr: &ruleRefExpr{
					pos:  position{line: 178, col: 15, offset: 6011},
					name: "Name",
				},
			},
		},
		{
			name: "Discard",
			pos:  position{line: 179, col: 1, offset: 6065},
			expr: &actionExpr{
				pos: position{line: 179, col: 12, offset: 6076},
				run: (*parser).callonDiscard1,
				expr: &ruleRefExpr{
					pos:  position{line: 179, col: 12, offset: 6076},
					name: "DiscardName",
				},
			},
		},
		{
			name: "Label",
			pos:  position{line: 180, col: 1, offset: 6134},
			expr: &actionExpr{
				pos: position{line: 180, col: 10, offset: 6143},
				run: (*parser).callonLabel1,
				expr: &ruleRefExpr{
					pos:  position{line: 180, col: 10, offset: 6143},
					name: "Name",
				},
			},
		},
		{
			name: "IgnoredContent",
			pos:  position{line: 182, col: 1, offset: 6180},
			expr: &actionExpr{
				pos: position{line: 182, col: 19, offset: 6198},
				run: (*parser).callonIgnoredContent1,
				expr: &oneOrMoreExpr{
					pos: position{line: 182, col: 19, offset: 6198},
					expr: &seqExpr{
						pos: position{line: 182, col: 20, offset: 6199},
						exprs: []any{
							&notExpr{
								pos: position{line: 182, col: 20, offset: 6199},
								expr: &choiceExpr{
									pos: position{line: 182, col: 22, offset: 6201},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 182, col: 22, offset: 6201},
											val:        "import",
											ignoreCase: false,
											want:       "\"import\"",
										},
										&litMatcher{
											pos:        position{line: 182, col: 33, offset: 6212},
											val:        "@external(",
											ignoreCase: false,
											want:       "\"@external(\"",
										},
										&seqExpr{
											pos: position{line: 182, col: 48, offset: 6227},
											exprs: []any{
												&litMatcher{
													pos:        position{line: 182, col: 48, offset: 6227},
													val:        "fn",
													ignoreCase: false,
													want:       "\"fn\"",
												},
												&ruleRefExpr{
													pos:  position{line: 182, col: 53, offset: 6232},
													name: "__",
												},
											},
										},
										&seqExpr{
											pos: position{line: 182, col: 58, offset: 6237},
											exprs: []any{
												&litMatcher{
													pos:        position{line: 182, col: 58, offset: 6237},
													val:        "pub",
													ignoreCase: false,
													want:       "\"pub\"",
												},
												&ruleRefExpr{
													pos:  position{line: 182, col: 64, offset: 6243},
													name: "__",
												},
												&litMatcher{
													pos:        position{line: 182, col: 67, offset: 6246},
													val:        "fn",
													ignoreCase: false,
													want:       "\"fn\"",
												},
												&ruleRefExpr{
													pos:  position{line: 182, col: 72, offset: 6251},
													name: "__",
												},
											},
										},
									},
								},
							},
							&anyMatcher{
								line: 182, col: 78, offset: 6257,
							},
						},
					},
				},
			},
		},
		{
			name: "IgnoredBlock",
			pos:  position{line: 183, col: 1, offset: 6281},
			expr: &actionExpr{
				pos: position{line: 183, col: 17, offset: 6297},
				run: (*parser).callonIgnoredBlock1,
				expr: &seqExpr{
					pos: position{line: 183, col: 17, offset: 6297},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 183, col: 17, offset: 6297},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 183, col: 21, offset: 6301},
							expr: &choiceExpr{
								pos: position{line: 183, col: 22, offset: 6302},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 183, col: 22, offset: 6302},
										name: "IgnoredBlock",
									},
									&seqExpr{
										pos: position{line: 183, col: 37, offset: 6317},
										exprs: []any{
											&notExpr{
												pos: position{line: 183, col: 37, offset: 6317},
												expr: &litMatcher{
													pos:        position{line: 183, col: 38, offset: 6318},
													val:        "}",
													ignoreCase: false,
													want:       "\"}\"",
												},
											},
											&anyMatcher{
												line: 183, col: 42, offset: 6322,
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 183, col: 46, offset: 6326},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 189, col: 1, offset: 6542},
			expr: &zeroOrMoreExpr{
				pos: position{line: 189, col: 19, offset: 6560},
				expr: &choiceExpr{
					pos: position{line: 189, col: 20, offset: 6561},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 189, col: 20, offset: 6561},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 189, col: 33, offset: 6574},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name:        "__",
			displayName: "\"whitespace\"",
			pos:         position{line: 190, col: 1, offset: 6584},
			expr: &oneOrMoreExpr{
				pos: position{line: 190, col: 20, offset: 6603},
				expr: &choiceExpr{
					pos: position{line: 190, col: 21, offset: 6604},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 190, col: 21, offset: 6604},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 34, offset: 6617},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 191, col: 1, offset: 6627},
			expr: &charClassMatcher{
				pos:        position{line: 191, col: 15, offset: 6641},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 192, col: 1, offset: 6651},
			expr: &actionExpr{
				pos: position{line: 192, col: 12, offset: 6662},
				run: (*parser).callonComment1,
				expr: &seqExpr{
					pos: position{line: 192, col: 12, offset: 6662},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 192, col: 12, offset: 6662},
							val:        "//",
							ignoreCase: false,
							want:       "\"//\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 192, col: 17, offset: 6667},
							expr: &seqExpr{
								pos: position{line: 192, col: 18, offset: 6668},
								exprs: []any{
									&notExpr{
										pos: position{line: 192, col: 18, offset: 6668},
										expr: &litMatcher{
											pos:        position{line: 192, col: 19, offset: 6669},
											val:        "\n",
											ignoreCase: false,
											want:       "\"\\n\"",
										},
									},
									&anyMatcher{
										line: 192, col: 24, offset: 6674,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Import",
			pos:  position{line: 198, col: 1, offset: 6904},
			expr: &actionExpr{
				pos: position{line: 198, col: 11, offset: 6914},
				run: (*parser).callonImport1,
				expr: &seqExpr{
					pos: position{line: 198, col: 11, offset: 6914},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 198, col: 11, offset: 6914},
							val:        "import",
							ignoreCase: false,
							want:       "\"import\"",
						},
						&ruleRefExpr{
							pos:  position{line: 198, col: 20, offset: 6923},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 198, col: 23, offset: 6926},
							label: "mod",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 27, offset: 6930},
								name: "Module",
							},
						},
						&labeledExpr{
							pos:   position{line: 198, col: 34, offset: 6937},
							label: "unqual",
							expr: &zeroOrOneExpr{
								pos: position{line: 198, col: 41, offset: 6944},
								expr: &seqExpr{
									pos: position{line: 198, col: 42, offset: 6945},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 198, col: 42, offset: 6945},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 198, col: 44, offset: 6947},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&ruleRefExpr{
											pos:  position{line: 198, col: 48, offset: 6951},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 198, col: 50, offset: 6953},
											name: "UnqualifiedImports",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 198, col: 71, offset: 6974},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 198, col: 77, offset: 6980},
								expr: &seqExpr{
									pos: position{line: 198, col: 78, offset: 6981},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 198, col: 78, offset: 6981},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 198, col: 80, offset: 6983},
											val:        "as",
											ignoreCase: false,
											want:       "\"as\"",
										},
										&ruleRefExpr{
											pos:  position{line: 198, col: 85, offset: 6988},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 198, col: 88, offset: 6991},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Module",
			pos:  position{line: 209, col: 1, offset: 7247},
			expr: &actionExpr{
				pos: position{line: 209, col: 11, offset: 7257},
				run: (*parser).callonModule1,
				expr: &seqExpr{
					pos: position{line: 209, col: 11, offset: 7257},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 209, col: 11, offset: 7257},
							name: "Name",
						},
						&zeroOrMoreExpr{
							pos: position{line: 209, col: 16, offset: 7262},
							expr: &seqExpr{
								pos: position{line: 209, col: 17, offset: 7263},
								exprs: []any{
									&ruleRefExpr{
										pos:  position{line: 209, col: 17, offset: 7263},
										name: "_",
									},
									&litMatcher{
										pos:        position{line: 209, col: 19, offset: 7265},
										val:        "/",
										ignoreCase: false,
										want:       "\"/\"",
									},
									&ruleRefExpr{
										pos:  position{line: 209, col: 23, offset: 7269},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 209, col: 25, offset: 7271},
										name: "Name",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "UnqualifiedImports",
			pos:  position{line: 214, col: 1, offset: 7389},
			expr: &actionExpr{
				pos: position{line: 214, col: 23, offset: 7411},
				run: (*parser).callonUnqualifiedImports1,
				expr: &seqExpr{
					pos: position{line: 214, col: 23, offset: 7411},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 214, col: 23, offset: 7411},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 214, col: 27, offset: 7415},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 214, col: 29, offset: 7417},
							label: "items",
							expr: &zeroOrOneExpr{
								pos: position{line: 214, col: 35, offset: 7423},
								expr: &ruleRefExpr{
									pos:  position{line: 214, col: 35, offset: 7423},
									name: "UnqualifiedImportList",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 214, col: 58, offset: 7446},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 214, col: 60, offset: 7448},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "UnqualifiedImportList",
			pos:  position{line: 222, col: 1, offset: 7622},
			expr: &actionExpr{
				pos: position{line: 222, col: 26, offset: 7647},
				run: (*parser).callonUnqualifiedImportList1,
				expr: &seqExpr{
					pos: position{line: 222, col: 26, offset: 7647},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 222, col: 26, offset: 7647},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 222, col: 32, offset: 7653},
								name: "UnqualifiedImport",
							},
						},
						&labeledExpr{
							pos:   position{line: 222, col: 50, offset: 7671},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 222, col: 55, offset: 7676},
								expr: &seqExpr{
									pos: position{line: 222, col: 56, offset: 7677},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 222, col: 56, offset: 7677},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 222, col: 58, offset: 7679},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 222, col: 62, offset: 7683},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 222, col: 64, offset: 7685},
											name: "UnqualifiedImport",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 222, col: 84, offset: 7705},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 222, col: 86, offset: 7707},
							expr: &litMatcher{
								pos:        position{line: 222, col: 86, offset: 7707},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
					},
				},
			},
		},
		{
			name: "UnqualifiedImport",
			pos:  position{line: 236, col: 1, offset: 8159},
			expr: &actionExpr{
				pos: position{line: 236, col: 22, offset: 8180},
				run: (*parser).callonUnqualifiedImport1,
				expr: &seqExpr{
					pos: position{line: 236, col: 22, offset: 8180},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 236, col: 22, offset: 8180},
							label: "itemType",
							expr: &zeroOrOneExpr{
								pos: position{line: 236, col: 31, offset: 8189},
								expr: &seqExpr{
									pos: position{line: 236, col: 32, offset: 8190},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 236, col: 32, offset: 8190},
											val:        "type",
											ignoreCase: false,
											want:       "\"type\"",
										},
										&ruleRefExpr{
											pos:  position{line: 236, col: 39, offset: 8197},
											name: "__",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 236, col: 44, offset: 8202},
							label: "name",
							expr: &choiceExpr{
								pos: position{line: 236, col: 50, offset: 8208},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 236, col: 50, offset: 8208},
										name: "UpName",
									},
									&ruleRefExpr{
										pos:  position{line: 236, col: 59, offset: 8217},
										name: "Name",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 236, col: 65, offset: 8223},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 236, col: 71, offset: 8229},
								expr: &seqExpr{
									pos: position{line: 236, col: 72, offset: 8230},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 236, col: 72, offset: 8230},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 236, col: 74, offset: 8232},
											val:        "as",
											ignoreCase: false,
											want:       "\"as\"",
										},
										&ruleRefExpr{
											pos:  position{line: 236, col: 79, offset: 8237},
											name: "__",
										},
										&choiceExpr{
											pos: position{line: 236, col: 83, offset: 8241},
											alternatives: []any{
												&ruleRefExpr{
													pos:  position{line: 236, col: 83, offset: 8241},
													name: "UpName",
												},
												&ruleRefExpr{
													pos:  position{line: 236, col: 92, offset: 8250},
													name: "Name",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Name",
			pos:  position{line: 252, col: 1, offset: 8634},
			expr: &actionExpr{
				pos: position{line: 252, col: 16, offset: 8649},
				run: (*parser).callonName1,
				expr: &seqExpr{
					pos: position{line: 252, col: 16, offset: 8649},
					exprs: []any{
						&notExpr{
							pos: position{line: 252, col: 16, offset: 8649},
							expr: &ruleRefExpr{
								pos:  position{line: 252, col: 17, offset: 8650},
								name: "KEYWORD",
							},
						},
						&charClassMatcher{
							pos:        position{line: 252, col: 25, offset: 8658},
							val:        "[a-z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 252, col: 32, offset: 8665},
							expr: &charClassMatcher{
								pos:        position{line: 252, col: 32, offset: 8665},
								val:        "[a-z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "UpName",
			pos:  position{line: 253, col: 1, offset: 8707},
			expr: &actionExpr{
				pos: position{line: 253, col: 16, offset: 8722},
				run: (*parser).callonUpName1,
				expr: &seqExpr{
					pos: position{line: 253, col: 16, offset: 8722},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 253, col: 16, offset: 8722},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 253, col: 22, offset: 8728},
							expr: &charClassMatcher{
								pos:        position{line: 253, col: 22, offset: 8728},
								val:        "[a-zA-Z0-9]",
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "DiscardName",
			pos:  position{line: 254, col: 1, offset: 8772},
			expr: &seqExpr{
				pos: position{line: 254, col: 16, offset: 8787},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 254, col: 16, offset: 8787},
						val:        "_",
						ignoreCase: false,
						want:       "\"_\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 254, col: 20, offset: 8791},
						expr: &charClassMatcher{
							pos:        position{line: 254, col: 20, offset: 8791},
							val:        "[a-z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "KEYWORD",
			pos:  position{line: 256, col: 1, offset: 8803},
			expr: &seqExpr{
				pos: position{line: 256, col: 12, offset: 8814},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 256, col: 13, offset: 8815},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 256, col: 13, offset: 8815},
								val:        "as",
								ignoreCase: false,
								want:       "\"as\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 20, offset: 8822},
								val:        "case",
								ignoreCase: false,
								want:       "\"case\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 29, offset: 8831},
								val:        "const",
								ignoreCase: false,
								want:       "\"const\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 39, offset: 8841},
								val:        "if",
								ignoreCase: false,
								want:       "\"if\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 46, offset: 8848},
								val:        "import",
								ignoreCase: false,
								want:       "\"import\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 57, offset: 8859},
								val:        "let",
								ignoreCase: false,
								want:       "\"let\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 65, offset: 8867},
								val:        "pub",
								ignoreCase: false,
								want:       "\"pub\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 73, offset: 8875},
								val:        "type",
								ignoreCase: false,
								want:       "\"type\"",
							},
							&litMatcher{
								pos:        position{line: 256, col: 82, offset: 8884},
								val:        "use",
								ignoreCase: false,
								want:       "\"use\"",
							},
						},
					},
					&notExpr{
						pos: position{line: 256, col: 89, offset: 8891},
						expr: &charClassMatcher{
							pos:        position{line: 256, col: 91, offset: 8893},
							val:        "[a-zA-Z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 257, col: 1, offset: 8907},
			expr: &notExpr{
				pos: position{line: 257, col: 12, offset: 8918},
				expr: &anyMatcher{
					line: 257, col: 13, offset: 8919,
				},
			},
		},
	},
}

func (c *current) onSourceFile1(first, rest any) (any, error) {
	if first == nil {
		return nil, nil
	}
	validStatements := []Node{first}
	if rest != nil {
		for _, s := range rest.([]any) {
			if s != nil {
				if val, ok := s.([]any); ok && val[1] != nil {
					validStatements = append(validStatements, val[1].(Node))
				}
			}
		}
	}
	return SourceFile{Statements: validStatements}, nil
}

func (p *parser) callonSourceFile1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSourceFile1(stack["first"], stack["rest"])
}

func (c *current) onFunction1(attrs, pub, name, params, returnGroup, body any) (any, error) {
	f := Function{Name: name.(string)}
	if pub != nil {
		f.Public = true
	}
	if params != nil {
		f.Parameters = params.([]Parameter)
	}
	if returnGroup != nil {
		f.ReturnType = returnGroup.([]any)[3].(Type)
	}
	if attrs != nil {
		f.ExternalAttributes = toSlice[ExternalAttribute](attrs)
	}
	return f, nil
}

func (p *parser) callonFunction1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["attrs"], stack["pub"], stack["name"], stack["params"], stack["returnGroup"], stack["body"])
}

func (c *current) onExternalAttribute1(args any) (any, error) {
	return args, nil
}

func (p *parser) callonExternalAttribute1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExternalAttribute1(stack["args"])
}

func (c *current) onExternalArgs1(target, module, function any) (any, error) {
	return ExternalAttribute{
		TargetLang: string(target.([]uint8)),
		Module:     strings.Trim(module.(string), "\""),
		Function:   strings.Trim(function.(string), "\""),
	}, nil
}

func (p *parser) callonExternalArgs1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExternalArgs1(stack["target"], stack["module"], stack["function"])
}

func (c *current) onStringArg1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonStringArg1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringArg1()
}

func (c *current) onFunctionParameters1(first, rest any) (any, error) {
	if first == nil {
		return []Parameter{}, nil
	}
	// Start the list with the first item. The type assertion is safe here.
	params := []Parameter{first.(Parameter)}

	// If there are more items, loop through them.
	if rest != nil {
		for _, paramPhrase := range toSlice[[]any](rest) {
			params = append(params, paramPhrase[3].(Parameter))
		}
	}
	return params, nil
}

func (p *parser) callonFunctionParameters1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionParameters1(stack["first"], stack["rest"])
}

func (c *current) onLambdaFunction1(first, rest, returnGroup any) (any, error) {
	return nil, nil
}

func (p *parser) callonLambdaFunction1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLambdaFunction1(stack["first"], stack["rest"], stack["returnGroup"])
}

func (c *current) onLambdaFunctionParameter1(t any) (any, error) {
	return t, nil
}

func (p *parser) callonLambdaFunctionParameter1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLambdaFunctionParameter1(stack["t"])
}

func (c *current) onFunctionParameter1(p, typ any) (any, error) {
	param, ok := p.(Parameter)
	if !ok {
		return nil, nil
	}
	if typ != nil {
		param.Type = typ.(Type)
	}
	return param, nil
}

func (p *parser) callonFunctionParameter1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionParameter1(stack["p"], stack["typ"])
}

func (c *current) onTypeAnnotation1(t any) (any, error) {
	return t, nil
}

func (p *parser) callonTypeAnnotation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotation1(stack["t"])
}

func (c *current) onTypeAnnotationContent1(t any) (any, error) {
	return t, nil
}

func (p *parser) callonTypeAnnotationContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotationContent1(stack["t"])
}

func (c *current) onTupleType1(first, rest any) (any, error) {
	return nil, nil
}

func (p *parser) callonTupleType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTupleType1(stack["first"], stack["rest"])
}

func (c *current) onType1(mod, name any) (any, error) {
	return name.(string), nil
}

func (p *parser) callonType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onType1(stack["mod"], stack["name"])
}

func (c *current) onGenericParams1(first, rest any) (any, error) {
	return nil, nil
}

func (p *parser) callonGenericParams1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGenericParams1(stack["first"], stack["rest"])
}

func (c *current) onGenericParam1(mod, param any) (any, error) {
	return nil, nil
}

func (p *parser) callonGenericParam1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGenericParam1(stack["mod"], stack["param"])
}

func (c *current) onLabeledNameParam1(label, name any) (any, error) {
	return Parameter{Label: label.(string), Name: name.(Identifier).Name}, nil
}

func (p *parser) callonLabeledNameParam1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLabeledNameParam1(stack["label"], stack["name"])
}

func (c *current) onNameParam1(name any) (any, error) {
	return Parameter{Name: name.(Identifier).Name}, nil
}

func (p *parser) callonNameParam1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNameParam1(stack["name"])
}

func (c *current) onDiscardParam1(name any) (any, error) {
	return Parameter{Name: name.(string)}, nil
}

func (p *parser) callonDiscardParam1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDiscardParam1(stack["name"])
}

func (c *current) onIdentifier1() (any, error) {
	return Identifier{Name: string(c.text)}, nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onDiscard1() (any, error) {
	return Discard{Name: string(c.text)}, nil
}

func (p *parser) callonDiscard1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDiscard1()
}

func (c *current) onLabel1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonLabel1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLabel1()
}

func (c *current) onIgnoredContent1() (any, error) {
	return nil, nil
}

func (p *parser) callonIgnoredContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIgnoredContent1()
}

func (c *current) onIgnoredBlock1() (any, error) {
	return nil, nil
}

func (p *parser) callonIgnoredBlock1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIgnoredBlock1()
}

func (c *current) onComment1() (any, error) {
	return nil, nil
}

func (p *parser) callonComment1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComment1()
}

func (c *current) onImport1(mod, unqual, alias any) (any, error) {
	imp := Import{Module: mod.(string)}
	if alias != nil {
		imp.Alias = alias.([]any)[3].(Identifier).Name
	}
	if unqual != nil {
		imp.Unqualified = unqual.([]any)[3].([]UnqualifiedImport)
	}
	return imp, nil
}

func (p *parser) callonImport1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onImport1(stack["mod"], stack["unqual"], stack["alias"])
}

func (c *current) onModule1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonModule1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onModule1()
}

func (c *current) onUnqualifiedImports1(items any) (any, error) {
	if items == nil {
		return []UnqualifiedImport{}, nil
	}
	return items, nil
}

func (p *parser) callonUnqualifiedImports1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnqualifiedImports1(stack["items"])
}

func (c *current) onUnqualifiedImportList1(first, rest any) (any, error) {
	// Start the list with the first item. The type assertion is safe here.
	imports := []UnqualifiedImport{first.(UnqualifiedImport)}

	// If there are more items, loop through them.
	if rest != nil {
		for _, pair := range toSlice[[]any](rest) {
			// Extract the UnqualifiedImport, which is the 4th element.
			imports = append(imports, pair[3].(UnqualifiedImport))
		}
	}
	return imports, nil
}

func (p *parser) callonUnqualifiedImportList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnqualifiedImportList1(stack["first"], stack["rest"])
}

func (c *current) onUnqualifiedImport1(itemType, name, alias any) (any, error) {
	imp := UnqualifiedImport{Name: name.(string)}
	if itemType != nil {
		imp.IsType = true
	}
	if alias != nil {
		imp.Alias = alias.([]any)[3].(string)
	}
	return imp, nil
}

func (p *parser) callonUnqualifiedImport1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnqualifiedImport1(stack["itemType"], stack["name"], stack["alias"])
}

func (c *current) onName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onName1()
}

func (c *current) onUpName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUpName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUpName1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
