// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

// -----------------------------------------------------------------------------
// ## Go Helper Code
// -----------------------------------------------------------------------------
func toSlice[T any](v any) []T {
	if v == nil {
		return nil
	}
	if s, ok := v.([]any); ok {
		res := make([]T, len(s))
		for i, item := range s {
			res[i] = item.(T)
		}
		return res
	}
	val, ok := v.(T)
	if !ok {
		panic(fmt.Sprintf("failed to convert to slice: unexpected type %T for target type %T", v, *new(T)))
	}
	return []T{val}
}

// Helper functions for parsing literals
func parseInteger(text []byte) (int64, error) {
	s := strings.ReplaceAll(string(text), "_", "")
	if len(s) > 2 {
		switch s[0:2] {
		case "0x", "0X":
			return strconv.ParseInt(s[2:], 16, 64)
		case "0o", "0O":
			return strconv.ParseInt(s[2:], 8, 64)
		case "0b", "0B":
			return strconv.ParseInt(s[2:], 2, 64)
		}
	}
	return strconv.ParseInt(s, 10, 64)
}

func parseFloat(text []byte) (float64, error) {
	s := strings.ReplaceAll(string(text), "_", "")
	return strconv.ParseFloat(s, 64)
}

func unquoteString(text []byte) (string, error) { return strconv.Unquote(string(text)) }

// -----------------------------------------------------------------------------
// ## AST Node Definitions
// -----------------------------------------------------------------------------

type Node interface{}
type Statement interface{ Node }
type Expression interface{ Node }
type Type interface{ Node }
type Pattern interface{ Node }

type SourceFile struct{ Statements []Node }
type Identifier struct{ Name string }
type Discard struct{ Name string }
type Parameter struct {
	Label, Name string
	Type        Type
}
type Function struct {
	Public     bool
	Name       string
	Parameters []Parameter
	ReturnType Type
}
type Import struct {
	Module      string
	Unqualified []UnqualifiedImport
	Alias       string
}

// Represents a single item in an unqualified import list, e.g., `MyType` in `import gleam.{MyType}`.
type UnqualifiedImport struct {
	Name   string
	Alias  string
	IsType bool // Differentiates `type MyType` from `MyFunction`
}

var g = &grammar{
	rules: []*rule{
		{
			name: "SourceFile",
			pos:  position{line: 81, col: 1, offset: 2397},
			expr: &actionExpr{
				pos: position{line: 81, col: 15, offset: 2411},
				run: (*parser).callonSourceFile1,
				expr: &seqExpr{
					pos: position{line: 81, col: 15, offset: 2411},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 81, col: 15, offset: 2411},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 81, col: 17, offset: 2413},
							label: "first",
							expr: &zeroOrOneExpr{
								pos: position{line: 81, col: 23, offset: 2419},
								expr: &choiceExpr{
									pos: position{line: 81, col: 24, offset: 2420},
									alternatives: []any{
										&ruleRefExpr{
											pos:  position{line: 81, col: 24, offset: 2420},
											name: "Import",
										},
										&ruleRefExpr{
											pos:  position{line: 81, col: 33, offset: 2429},
											name: "MainFunction",
										},
										&ruleRefExpr{
											pos:  position{line: 81, col: 48, offset: 2444},
											name: "IgnoredContent",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 81, col: 65, offset: 2461},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 81, col: 70, offset: 2466},
								expr: &seqExpr{
									pos: position{line: 81, col: 71, offset: 2467},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 81, col: 71, offset: 2467},
											name: "_",
										},
										&choiceExpr{
											pos: position{line: 81, col: 74, offset: 2470},
											alternatives: []any{
												&ruleRefExpr{
													pos:  position{line: 81, col: 74, offset: 2470},
													name: "Import",
												},
												&ruleRefExpr{
													pos:  position{line: 81, col: 83, offset: 2479},
													name: "MainFunction",
												},
												&ruleRefExpr{
													pos:  position{line: 81, col: 98, offset: 2494},
													name: "IgnoredContent",
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 81, col: 116, offset: 2512},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 81, col: 118, offset: 2514},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "MainFunction",
			pos:  position{line: 98, col: 1, offset: 2905},
			expr: &actionExpr{
				pos: position{line: 98, col: 17, offset: 2921},
				run: (*parser).callonMainFunction1,
				expr: &seqExpr{
					pos: position{line: 98, col: 17, offset: 2921},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 98, col: 17, offset: 2921},
							label: "pub",
							expr: &zeroOrOneExpr{
								pos: position{line: 98, col: 21, offset: 2925},
								expr: &seqExpr{
									pos: position{line: 98, col: 22, offset: 2926},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 98, col: 22, offset: 2926},
											val:        "pub",
											ignoreCase: false,
											want:       "\"pub\"",
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 28, offset: 2932},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 98, col: 33, offset: 2937},
							val:        "fn",
							ignoreCase: false,
							want:       "\"fn\"",
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 38, offset: 2942},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 98, col: 41, offset: 2945},
							val:        "main",
							ignoreCase: false,
							want:       "\"main\"",
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 48, offset: 2952},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 98, col: 50, offset: 2954},
							label: "params",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 57, offset: 2961},
								name: "FunctionParameters",
							},
						},
						&labeledExpr{
							pos:   position{line: 98, col: 76, offset: 2980},
							label: "returnGroup",
							expr: &zeroOrOneExpr{
								pos: position{line: 98, col: 88, offset: 2992},
								expr: &seqExpr{
									pos: position{line: 98, col: 89, offset: 2993},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 98, col: 89, offset: 2993},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 98, col: 91, offset: 2995},
											val:        "->",
											ignoreCase: false,
											want:       "\"->\"",
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 96, offset: 3000},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 98, offset: 3002},
											name: "Type",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 105, offset: 3009},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 98, col: 107, offset: 3011},
							label: "body",
							expr: &zeroOrOneExpr{
								pos: position{line: 98, col: 112, offset: 3016},
								expr: &ruleRefExpr{
									pos:  position{line: 98, col: 112, offset: 3016},
									name: "IgnoredBlock",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionParameters",
			pos:  position{line: 108, col: 1, offset: 3377},
			expr: &actionExpr{
				pos: position{line: 108, col: 23, offset: 3399},
				run: (*parser).callonFunctionParameters1,
				expr: &seqExpr{
					pos: position{line: 108, col: 23, offset: 3399},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 108, col: 23, offset: 3399},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 108, col: 27, offset: 3403},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 108, col: 29, offset: 3405},
							label: "params",
							expr: &zeroOrOneExpr{
								pos: position{line: 108, col: 36, offset: 3412},
								expr: &seqExpr{
									pos: position{line: 108, col: 37, offset: 3413},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 108, col: 37, offset: 3413},
											name: "FunctionParameter",
										},
										&zeroOrMoreExpr{
											pos: position{line: 108, col: 55, offset: 3431},
											expr: &seqExpr{
												pos: position{line: 108, col: 56, offset: 3432},
												exprs: []any{
													&ruleRefExpr{
														pos:  position{line: 108, col: 56, offset: 3432},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 108, col: 58, offset: 3434},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 108, col: 62, offset: 3438},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 108, col: 64, offset: 3440},
														name: "FunctionParameter",
													},
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 108, col: 84, offset: 3460},
											name: "_",
										},
										&zeroOrOneExpr{
											pos: position{line: 108, col: 86, offset: 3462},
											expr: &litMatcher{
												pos:        position{line: 108, col: 86, offset: 3462},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 108, col: 93, offset: 3469},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 108, col: 95, offset: 3471},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "FunctionParameter",
			pos:  position{line: 112, col: 1, offset: 3520},
			expr: &actionExpr{
				pos: position{line: 112, col: 22, offset: 3541},
				run: (*parser).callonFunctionParameter1,
				expr: &seqExpr{
					pos: position{line: 112, col: 22, offset: 3541},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 112, col: 22, offset: 3541},
							label: "p",
							expr: &choiceExpr{
								pos: position{line: 112, col: 25, offset: 3544},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 112, col: 25, offset: 3544},
										name: "LabeledNameParam",
									},
									&ruleRefExpr{
										pos:  position{line: 112, col: 44, offset: 3563},
										name: "NameParam",
									},
									&ruleRefExpr{
										pos:  position{line: 112, col: 56, offset: 3575},
										name: "DiscardParam",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 112, col: 70, offset: 3589},
							label: "typ",
							expr: &zeroOrOneExpr{
								pos: position{line: 112, col: 74, offset: 3593},
								expr: &ruleRefExpr{
									pos:  position{line: 112, col: 74, offset: 3593},
									name: "TypeAnnotation",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TypeAnnotation",
			pos:  position{line: 117, col: 1, offset: 3699},
			expr: &actionExpr{
				pos: position{line: 117, col: 19, offset: 3717},
				run: (*parser).callonTypeAnnotation1,
				expr: &seqExpr{
					pos: position{line: 117, col: 19, offset: 3717},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 117, col: 19, offset: 3717},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 23, offset: 3721},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 117, col: 25, offset: 3723},
							label: "t",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 27, offset: 3725},
								name: "Type",
							},
						},
					},
				},
			},
		},
		{
			name: "Type",
			pos:  position{line: 118, col: 1, offset: 3748},
			expr: &ruleRefExpr{
				pos:  position{line: 118, col: 9, offset: 3756},
				name: "Identifier",
			},
		},
		{
			name: "LabeledNameParam",
			pos:  position{line: 119, col: 1, offset: 3789},
			expr: &actionExpr{
				pos: position{line: 119, col: 21, offset: 3809},
				run: (*parser).callonLabeledNameParam1,
				expr: &seqExpr{
					pos: position{line: 119, col: 21, offset: 3809},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 119, col: 21, offset: 3809},
							label: "label",
							expr: &ruleRefExpr{
								pos:  position{line: 119, col: 27, offset: 3815},
								name: "Label",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 33, offset: 3821},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 119, col: 35, offset: 3823},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 119, col: 40, offset: 3828},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "NameParam",
			pos:  position{line: 122, col: 1, offset: 3919},
			expr: &actionExpr{
				pos: position{line: 122, col: 14, offset: 3932},
				run: (*parser).callonNameParam1,
				expr: &labeledExpr{
					pos:   position{line: 122, col: 14, offset: 3932},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 122, col: 19, offset: 3937},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "DiscardParam",
			pos:  position{line: 123, col: 1, offset: 4004},
			expr: &actionExpr{
				pos: position{line: 123, col: 17, offset: 4020},
				run: (*parser).callonDiscardParam1,
				expr: &labeledExpr{
					pos:   position{line: 123, col: 17, offset: 4020},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 123, col: 22, offset: 4025},
						name: "Discard",
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 124, col: 1, offset: 4080},
			expr: &actionExpr{
				pos: position{line: 124, col: 15, offset: 4094},
				run: (*parser).callonIdentifier1,
				expr: &ruleRefExpr{
					pos:  position{line: 124, col: 15, offset: 4094},
					name: "Name",
				},
			},
		},
		{
			name: "Discard",
			pos:  position{line: 125, col: 1, offset: 4148},
			expr: &actionExpr{
				pos: position{line: 125, col: 12, offset: 4159},
				run: (*parser).callonDiscard1,
				expr: &ruleRefExpr{
					pos:  position{line: 125, col: 12, offset: 4159},
					name: "DiscardName",
				},
			},
		},
		{
			name: "Label",
			pos:  position{line: 126, col: 1, offset: 4217},
			expr: &actionExpr{
				pos: position{line: 126, col: 10, offset: 4226},
				run: (*parser).callonLabel1,
				expr: &ruleRefExpr{
					pos:  position{line: 126, col: 10, offset: 4226},
					name: "Name",
				},
			},
		},
		{
			name: "IgnoredContent",
			pos:  position{line: 128, col: 1, offset: 4263},
			expr: &actionExpr{
				pos: position{line: 128, col: 19, offset: 4281},
				run: (*parser).callonIgnoredContent1,
				expr: &oneOrMoreExpr{
					pos: position{line: 128, col: 19, offset: 4281},
					expr: &seqExpr{
						pos: position{line: 128, col: 20, offset: 4282},
						exprs: []any{
							&notExpr{
								pos: position{line: 128, col: 20, offset: 4282},
								expr: &choiceExpr{
									pos: position{line: 128, col: 22, offset: 4284},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 128, col: 22, offset: 4284},
											val:        "import",
											ignoreCase: false,
											want:       "\"import\"",
										},
										&seqExpr{
											pos: position{line: 128, col: 33, offset: 4295},
											exprs: []any{
												&litMatcher{
													pos:        position{line: 128, col: 33, offset: 4295},
													val:        "pub",
													ignoreCase: false,
													want:       "\"pub\"",
												},
												&ruleRefExpr{
													pos:  position{line: 128, col: 39, offset: 4301},
													name: "__",
												},
												&litMatcher{
													pos:        position{line: 128, col: 42, offset: 4304},
													val:        "fn",
													ignoreCase: false,
													want:       "\"fn\"",
												},
												&ruleRefExpr{
													pos:  position{line: 128, col: 47, offset: 4309},
													name: "__",
												},
												&litMatcher{
													pos:        position{line: 128, col: 50, offset: 4312},
													val:        "main",
													ignoreCase: false,
													want:       "\"main\"",
												},
											},
										},
									},
								},
							},
							&anyMatcher{
								line: 128, col: 58, offset: 4320,
							},
						},
					},
				},
			},
		},
		{
			name: "IgnoredBlock",
			pos:  position{line: 129, col: 1, offset: 4344},
			expr: &actionExpr{
				pos: position{line: 129, col: 17, offset: 4360},
				run: (*parser).callonIgnoredBlock1,
				expr: &seqExpr{
					pos: position{line: 129, col: 17, offset: 4360},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 129, col: 17, offset: 4360},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 129, col: 21, offset: 4364},
							expr: &choiceExpr{
								pos: position{line: 129, col: 22, offset: 4365},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 129, col: 22, offset: 4365},
										name: "IgnoredBlock",
									},
									&seqExpr{
										pos: position{line: 129, col: 37, offset: 4380},
										exprs: []any{
											&notExpr{
												pos: position{line: 129, col: 37, offset: 4380},
												expr: &litMatcher{
													pos:        position{line: 129, col: 38, offset: 4381},
													val:        "}",
													ignoreCase: false,
													want:       "\"}\"",
												},
											},
											&anyMatcher{
												line: 129, col: 42, offset: 4385,
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 129, col: 46, offset: 4389},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 135, col: 1, offset: 4605},
			expr: &zeroOrMoreExpr{
				pos: position{line: 135, col: 19, offset: 4623},
				expr: &choiceExpr{
					pos: position{line: 135, col: 20, offset: 4624},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 135, col: 20, offset: 4624},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 135, col: 33, offset: 4637},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name:        "__",
			displayName: "\"whitespace\"",
			pos:         position{line: 136, col: 1, offset: 4647},
			expr: &oneOrMoreExpr{
				pos: position{line: 136, col: 20, offset: 4666},
				expr: &choiceExpr{
					pos: position{line: 136, col: 21, offset: 4667},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 136, col: 21, offset: 4667},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 136, col: 34, offset: 4680},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 137, col: 1, offset: 4690},
			expr: &charClassMatcher{
				pos:        position{line: 137, col: 15, offset: 4704},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 138, col: 1, offset: 4714},
			expr: &actionExpr{
				pos: position{line: 138, col: 12, offset: 4725},
				run: (*parser).callonComment1,
				expr: &seqExpr{
					pos: position{line: 138, col: 12, offset: 4725},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 138, col: 12, offset: 4725},
							val:        "//",
							ignoreCase: false,
							want:       "\"//\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 138, col: 17, offset: 4730},
							expr: &seqExpr{
								pos: position{line: 138, col: 18, offset: 4731},
								exprs: []any{
									&notExpr{
										pos: position{line: 138, col: 18, offset: 4731},
										expr: &litMatcher{
											pos:        position{line: 138, col: 19, offset: 4732},
											val:        "\n",
											ignoreCase: false,
											want:       "\"\\n\"",
										},
									},
									&anyMatcher{
										line: 138, col: 24, offset: 4737,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Import",
			pos:  position{line: 144, col: 1, offset: 4967},
			expr: &actionExpr{
				pos: position{line: 144, col: 11, offset: 4977},
				run: (*parser).callonImport1,
				expr: &seqExpr{
					pos: position{line: 144, col: 11, offset: 4977},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 144, col: 11, offset: 4977},
							val:        "import",
							ignoreCase: false,
							want:       "\"import\"",
						},
						&ruleRefExpr{
							pos:  position{line: 144, col: 20, offset: 4986},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 144, col: 23, offset: 4989},
							label: "mod",
							expr: &ruleRefExpr{
								pos:  position{line: 144, col: 27, offset: 4993},
								name: "Module",
							},
						},
						&labeledExpr{
							pos:   position{line: 144, col: 34, offset: 5000},
							label: "unqual",
							expr: &zeroOrOneExpr{
								pos: position{line: 144, col: 41, offset: 5007},
								expr: &seqExpr{
									pos: position{line: 144, col: 42, offset: 5008},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 144, col: 42, offset: 5008},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 144, col: 44, offset: 5010},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&ruleRefExpr{
											pos:  position{line: 144, col: 48, offset: 5014},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 144, col: 50, offset: 5016},
											name: "UnqualifiedImports",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 144, col: 71, offset: 5037},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 144, col: 77, offset: 5043},
								expr: &seqExpr{
									pos: position{line: 144, col: 78, offset: 5044},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 144, col: 78, offset: 5044},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 144, col: 80, offset: 5046},
											val:        "as",
											ignoreCase: false,
											want:       "\"as\"",
										},
										&ruleRefExpr{
											pos:  position{line: 144, col: 85, offset: 5051},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 144, col: 88, offset: 5054},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Module",
			pos:  position{line: 155, col: 1, offset: 5310},
			expr: &actionExpr{
				pos: position{line: 155, col: 11, offset: 5320},
				run: (*parser).callonModule1,
				expr: &seqExpr{
					pos: position{line: 155, col: 11, offset: 5320},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 155, col: 11, offset: 5320},
							name: "Name",
						},
						&zeroOrMoreExpr{
							pos: position{line: 155, col: 16, offset: 5325},
							expr: &seqExpr{
								pos: position{line: 155, col: 17, offset: 5326},
								exprs: []any{
									&ruleRefExpr{
										pos:  position{line: 155, col: 17, offset: 5326},
										name: "_",
									},
									&litMatcher{
										pos:        position{line: 155, col: 19, offset: 5328},
										val:        "/",
										ignoreCase: false,
										want:       "\"/\"",
									},
									&ruleRefExpr{
										pos:  position{line: 155, col: 23, offset: 5332},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 155, col: 25, offset: 5334},
										name: "Name",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "UnqualifiedImports",
			pos:  position{line: 160, col: 1, offset: 5452},
			expr: &actionExpr{
				pos: position{line: 160, col: 23, offset: 5474},
				run: (*parser).callonUnqualifiedImports1,
				expr: &seqExpr{
					pos: position{line: 160, col: 23, offset: 5474},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 160, col: 23, offset: 5474},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 160, col: 27, offset: 5478},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 160, col: 29, offset: 5480},
							label: "items",
							expr: &zeroOrOneExpr{
								pos: position{line: 160, col: 35, offset: 5486},
								expr: &ruleRefExpr{
									pos:  position{line: 160, col: 35, offset: 5486},
									name: "UnqualifiedImportList",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 160, col: 58, offset: 5509},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 160, col: 60, offset: 5511},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "UnqualifiedImportList",
			pos:  position{line: 168, col: 1, offset: 5685},
			expr: &actionExpr{
				pos: position{line: 168, col: 26, offset: 5710},
				run: (*parser).callonUnqualifiedImportList1,
				expr: &seqExpr{
					pos: position{line: 168, col: 26, offset: 5710},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 168, col: 26, offset: 5710},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 168, col: 32, offset: 5716},
								name: "UnqualifiedImport",
							},
						},
						&labeledExpr{
							pos:   position{line: 168, col: 50, offset: 5734},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 168, col: 55, offset: 5739},
								expr: &seqExpr{
									pos: position{line: 168, col: 56, offset: 5740},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 168, col: 56, offset: 5740},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 168, col: 58, offset: 5742},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 168, col: 62, offset: 5746},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 168, col: 64, offset: 5748},
											name: "UnqualifiedImport",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 168, col: 84, offset: 5768},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 168, col: 86, offset: 5770},
							expr: &litMatcher{
								pos:        position{line: 168, col: 86, offset: 5770},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
					},
				},
			},
		},
		{
			name: "UnqualifiedImport",
			pos:  position{line: 182, col: 1, offset: 6222},
			expr: &actionExpr{
				pos: position{line: 182, col: 22, offset: 6243},
				run: (*parser).callonUnqualifiedImport1,
				expr: &seqExpr{
					pos: position{line: 182, col: 22, offset: 6243},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 182, col: 22, offset: 6243},
							label: "itemType",
							expr: &zeroOrOneExpr{
								pos: position{line: 182, col: 31, offset: 6252},
								expr: &seqExpr{
									pos: position{line: 182, col: 32, offset: 6253},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 182, col: 32, offset: 6253},
											val:        "type",
											ignoreCase: false,
											want:       "\"type\"",
										},
										&ruleRefExpr{
											pos:  position{line: 182, col: 39, offset: 6260},
											name: "__",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 182, col: 44, offset: 6265},
							label: "name",
							expr: &choiceExpr{
								pos: position{line: 182, col: 50, offset: 6271},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 182, col: 50, offset: 6271},
										name: "UpName",
									},
									&ruleRefExpr{
										pos:  position{line: 182, col: 59, offset: 6280},
										name: "Name",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 182, col: 65, offset: 6286},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 182, col: 71, offset: 6292},
								expr: &seqExpr{
									pos: position{line: 182, col: 72, offset: 6293},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 182, col: 72, offset: 6293},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 182, col: 74, offset: 6295},
											val:        "as",
											ignoreCase: false,
											want:       "\"as\"",
										},
										&ruleRefExpr{
											pos:  position{line: 182, col: 79, offset: 6300},
											name: "__",
										},
										&choiceExpr{
											pos: position{line: 182, col: 83, offset: 6304},
											alternatives: []any{
												&ruleRefExpr{
													pos:  position{line: 182, col: 83, offset: 6304},
													name: "UpName",
												},
												&ruleRefExpr{
													pos:  position{line: 182, col: 92, offset: 6313},
													name: "Name",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Name",
			pos:  position{line: 198, col: 1, offset: 6697},
			expr: &actionExpr{
				pos: position{line: 198, col: 16, offset: 6712},
				run: (*parser).callonName1,
				expr: &seqExpr{
					pos: position{line: 198, col: 16, offset: 6712},
					exprs: []any{
						&notExpr{
							pos: position{line: 198, col: 16, offset: 6712},
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 17, offset: 6713},
								name: "KEYWORD",
							},
						},
						&charClassMatcher{
							pos:        position{line: 198, col: 25, offset: 6721},
							val:        "[a-z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 198, col: 32, offset: 6728},
							expr: &charClassMatcher{
								pos:        position{line: 198, col: 32, offset: 6728},
								val:        "[a-z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "UpName",
			pos:  position{line: 199, col: 1, offset: 6770},
			expr: &actionExpr{
				pos: position{line: 199, col: 16, offset: 6785},
				run: (*parser).callonUpName1,
				expr: &seqExpr{
					pos: position{line: 199, col: 16, offset: 6785},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 199, col: 16, offset: 6785},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 199, col: 22, offset: 6791},
							expr: &charClassMatcher{
								pos:        position{line: 199, col: 22, offset: 6791},
								val:        "[a-zA-Z0-9]",
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "DiscardName",
			pos:  position{line: 200, col: 1, offset: 6835},
			expr: &seqExpr{
				pos: position{line: 200, col: 16, offset: 6850},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 200, col: 16, offset: 6850},
						val:        "_",
						ignoreCase: false,
						want:       "\"_\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 200, col: 20, offset: 6854},
						expr: &charClassMatcher{
							pos:        position{line: 200, col: 20, offset: 6854},
							val:        "[a-z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "KEYWORD",
			pos:  position{line: 202, col: 1, offset: 6866},
			expr: &seqExpr{
				pos: position{line: 202, col: 12, offset: 6877},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 202, col: 13, offset: 6878},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 202, col: 13, offset: 6878},
								val:        "as",
								ignoreCase: false,
								want:       "\"as\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 20, offset: 6885},
								val:        "case",
								ignoreCase: false,
								want:       "\"case\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 29, offset: 6894},
								val:        "const",
								ignoreCase: false,
								want:       "\"const\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 39, offset: 6904},
								val:        "if",
								ignoreCase: false,
								want:       "\"if\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 46, offset: 6911},
								val:        "import",
								ignoreCase: false,
								want:       "\"import\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 57, offset: 6922},
								val:        "let",
								ignoreCase: false,
								want:       "\"let\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 65, offset: 6930},
								val:        "pub",
								ignoreCase: false,
								want:       "\"pub\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 73, offset: 6938},
								val:        "type",
								ignoreCase: false,
								want:       "\"type\"",
							},
							&litMatcher{
								pos:        position{line: 202, col: 82, offset: 6947},
								val:        "use",
								ignoreCase: false,
								want:       "\"use\"",
							},
						},
					},
					&notExpr{
						pos: position{line: 202, col: 89, offset: 6954},
						expr: &charClassMatcher{
							pos:        position{line: 202, col: 91, offset: 6956},
							val:        "[a-zA-Z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 203, col: 1, offset: 6970},
			expr: &notExpr{
				pos: position{line: 203, col: 12, offset: 6981},
				expr: &anyMatcher{
					line: 203, col: 13, offset: 6982,
				},
			},
		},
	},
}

func (c *current) onSourceFile1(first, rest any) (any, error) {
	if first == nil {
		return nil, nil
	}
	validStatements := []Node{first}
	if rest != nil {
		for _, s := range rest.([]any) {
			if s != nil {
				if val, ok := s.([]any); ok && val[1] != nil {
					validStatements = append(validStatements, val[1].(Node))
				}
			}
		}
	}
	return SourceFile{Statements: validStatements}, nil
}

func (p *parser) callonSourceFile1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSourceFile1(stack["first"], stack["rest"])
}

func (c *current) onMainFunction1(pub, params, returnGroup, body any) (any, error) {
	// We hardcode the name to "main"
	f := Function{Name: "main"}
	if pub != nil {
		f.Public = true
	}
	if params != nil {
		f.Parameters = params.([]Parameter)
	}
	// The body is ignored, but you could capture it as a raw string if needed.
	if returnGroup != nil {
		f.ReturnType = returnGroup.([]any)[3].(Type)
	}
	return f, nil
}

func (p *parser) callonMainFunction1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMainFunction1(stack["pub"], stack["params"], stack["returnGroup"], stack["body"])
}

func (c *current) onFunctionParameters1(params any) (any, error) {
	return toSlice[Parameter](params), nil
}

func (p *parser) callonFunctionParameters1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionParameters1(stack["params"])
}

func (c *current) onFunctionParameter1(p, typ any) (any, error) {
	param := p.(Parameter)
	if typ != nil {
		param.Type = typ.(Type)
	}
	return param, nil
}

func (p *parser) callonFunctionParameter1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionParameter1(stack["p"], stack["typ"])
}

func (c *current) onTypeAnnotation1(t any) (any, error) {
	return t, nil
}

func (p *parser) callonTypeAnnotation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotation1(stack["t"])
}

func (c *current) onLabeledNameParam1(label, name any) (any, error) {
	return Parameter{Label: label.(string), Name: name.(Identifier).Name}, nil
}

func (p *parser) callonLabeledNameParam1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLabeledNameParam1(stack["label"], stack["name"])
}

func (c *current) onNameParam1(name any) (any, error) {
	return Parameter{Name: name.(Identifier).Name}, nil
}

func (p *parser) callonNameParam1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNameParam1(stack["name"])
}

func (c *current) onDiscardParam1(name any) (any, error) {
	return Parameter{Name: name.(string)}, nil
}

func (p *parser) callonDiscardParam1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDiscardParam1(stack["name"])
}

func (c *current) onIdentifier1() (any, error) {
	return Identifier{Name: string(c.text)}, nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onDiscard1() (any, error) {
	return Discard{Name: string(c.text)}, nil
}

func (p *parser) callonDiscard1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDiscard1()
}

func (c *current) onLabel1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonLabel1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLabel1()
}

func (c *current) onIgnoredContent1() (any, error) {
	return nil, nil
}

func (p *parser) callonIgnoredContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIgnoredContent1()
}

func (c *current) onIgnoredBlock1() (any, error) {
	return nil, nil
}

func (p *parser) callonIgnoredBlock1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIgnoredBlock1()
}

func (c *current) onComment1() (any, error) {
	return nil, nil
}

func (p *parser) callonComment1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComment1()
}

func (c *current) onImport1(mod, unqual, alias any) (any, error) {
	imp := Import{Module: mod.(string)}
	if alias != nil {
		imp.Alias = alias.([]any)[3].(Identifier).Name
	}
	if unqual != nil {
		imp.Unqualified = unqual.([]any)[3].([]UnqualifiedImport)
	}
	return imp, nil
}

func (p *parser) callonImport1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onImport1(stack["mod"], stack["unqual"], stack["alias"])
}

func (c *current) onModule1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonModule1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onModule1()
}

func (c *current) onUnqualifiedImports1(items any) (any, error) {
	if items == nil {
		return []UnqualifiedImport{}, nil
	}
	return items, nil
}

func (p *parser) callonUnqualifiedImports1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnqualifiedImports1(stack["items"])
}

func (c *current) onUnqualifiedImportList1(first, rest any) (any, error) {
	// Start the list with the first item. The type assertion is safe here.
	imports := []UnqualifiedImport{first.(UnqualifiedImport)}

	// If there are more items, loop through them.
	if rest != nil {
		for _, pair := range toSlice[[]any](rest) {
			// Extract the UnqualifiedImport, which is the 4th element.
			imports = append(imports, pair[3].(UnqualifiedImport))
		}
	}
	return imports, nil
}

func (p *parser) callonUnqualifiedImportList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnqualifiedImportList1(stack["first"], stack["rest"])
}

func (c *current) onUnqualifiedImport1(itemType, name, alias any) (any, error) {
	imp := UnqualifiedImport{Name: name.(string)}
	if itemType != nil {
		imp.IsType = true
	}
	if alias != nil {
		imp.Alias = alias.([]any)[3].(string)
	}
	return imp, nil
}

func (p *parser) callonUnqualifiedImport1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnqualifiedImport1(stack["itemType"], stack["name"], stack["alias"])
}

func (c *current) onName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onName1()
}

func (c *current) onUpName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUpName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUpName1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
