#!/bin/sh
#
# This file is generated by rules_gleam. DO NOT EDIT.

set -eu

PACKAGE={PACKAGE}
BASE=$(echo "$0.runfiles/_main")

run() {
  exec erl \
    -pa "$BASE" \
    -eval "$PACKAGE@@main:run($PACKAGE)" \
    -noshell \
    -extra "$@"
}

run "$@"