load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "wspace",
    srcs = ["finder.go"],
    importpath = "github.com/iocat/rules_gleam/internal/tools/gazelle/wspace",
    visibility = ["//:__subpackages__"],
)
