name = "todo"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[scripts]
test = "gleam test"
run = "gleam run -m todo"
