# Cut a release whenever a new tag is pushed to the repo.
name: Release
on:
  # Run the publish workflow after a successful release
  # Will be triggered from the release.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      BCR_PUBLISH_TOKEN:
        required: true
  # In case of problems, let release engineers retry by manually dispatching
  # the workflow from the GitHub UI
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write # Needed to attest provenance
  attestations: write # Needed to attest provenance
  contents: write # Needed to create release

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.3
    with:
      release_files: rules_gleam-*.tar.gz
      prerelease: false
      tag_name: ${{ inputs.tag_name || github.ref_name }}
  publish:
    needs: release
    uses: ./.github/workflows/publish.yml
    with:
        tag_name: ${{ inputs.tag_name || github.ref_name }}
    secrets:
      BCR_PUBLISH_TOKEN: ${{ secrets.BCR_PUBLISH_TOKEN }}
   