name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.12.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - uses: bazel-contrib/setup-bazel@0.8.1
      - name: test gazelle
        run: bazel test //gazelle/...
      - name: test example
        run: |
          cd examples/basic
          bazel test //gazelle/...
