name: Test

on:
  push:
    branches:
      - master
      - main
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.1
      - name: test all
        run: |
          bazel test //gazelle/...
          bazel test //internal/tools/...
      - name: test examples
        run: |
          cd examples/basic
          bazel build //...
          tree bazel-out/k8-fastbuild/bin/example.sh.runfiles/rules_gleam++gleam+gleam_erlang_compiler_x86_64_linux_gnu/usr/local/lib/erlang/bin
          cat bazel-out/k8-fastbuild/bin/example.sh.runfiles/_main/example.sh
          bazel test  --test_output=streamed //...
          cd ../..
          cd examples/httpserver
          bazel build //...
          cd ../..
