name = "httpserver"
dependencies = { mist = ">= 5.0.3 and < 6.0.0" , logging = ">= 1.3.0 and < 2.0.0" , gleam_stdlib = ">= 0.65.0 and < 1.0.0", gleam_erlang = ">= 1.3.0 and < 2.0.0", gleam_http = ">= 4.3.0 and < 5.0.0", gleam_otp = ">= 1.2.0 and < 2.0.0", gleam_yielder = ">= 1.1.0 and < 2.0.0" }
